### PR TITLE
Removed deprecated partition-file feature

### LINKED ISSUE #273: Remove the partition-file feature as its deprecated after the new track-run feature.
Partition-file feature was used to log any token-ranges that fails for any reasons. These failed token-ranges would then we loaded in the next run to optimally run `migration` or `validation` on those specific token-ranges to reduce the time taken by reruns.

This feature is now deprecated as the track-run feature does that (logs token-ranges that failed as well as one that has validation differences) and more. The new track-run feature is also more Spark complaint when running on a Spark cluster & does not depend on a local disk.

### PR DESCRIPTION
**Pull request by pravinbhat**
**What this PR does**:
Remove the partition-file feature as its deprecated after the new track-run feature.

**Which issue(s) this PR fixes**:
Fixes #273 

**Checklist:**
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by msmygit — APPROVED** [review]
lgtm, but one question - how do we migrate/validate just a token range with the new approach, if need be. Should we document that as well too?

**Comment by pravinbhat** [comment]
> lgtm, but one question - how do we migrate/validate just a token range with the new approach, if need be. Should we document that as well too?

Support for Migrating a specific token-range will continue unchanged using the partition `min/max` [feature](https://github.com/datastax/cassandra-data-migrator/blob/issue/remove-partition-file-feature/src/resources/cdm-detailed.properties#L293). However if you have to migrate several distinct token-ranges, you may have to manually create a run in the `cdm_run` tables, which may be not be as convenient as listing those token-ranges in the `partition-file` as currently supported. Having said that, I have not seen a need for this other then for processing failed partitions. Also the new DB based handling is more spark complaint (single point of reference for distributed compute VMs) than the current output  file based approach.

Do you think we should document the `min/max` feature in the readme? Overall I like the idea of keeping the readme only for highly used featutes and the rest in the detailed properties.

**Comment by faizalrub-datastax** [comment]
Catching up with these changes :).  With large migrations/validations, there are scenarios where multiple partition ranges get logged in the partition range file. During the rerun, the job only processes the errored ranges. How will this be handled with the recent changes?

**Comment by pravinbhat** [comment]
> Catching up with these changes :). With large migrations/validations, there are scenarios where multiple partition ranges get logged in the partition range file. During the rerun, the job only processes the errored ranges. How will this be handled with the recent changes?

That will be fully supported & is the whole nature of these changes. All failed (& more) partitions will be tracked in the DB as part of the `track-run` feature instead of partition-file (deprecated feature). The `track-run` generates a unique `run-id` for each run, so if for any reason you need to rerun a job that previous failed or was in-complete, just pass the previous-run-id & the new job will just resume & process only the `token-ranges` that had `failed` or `not processed`.

**Review by Jeremya — APPROVED** [review]

**Pull request merged**
