### PR TITLE
Move contributors to CONTRIBUTING.md file. Create an initial version …

### PR DESCRIPTION
**Pull request by msmygit**
…of code of conduct

### CODE REVIEW

**Review by faizalrub-datastax — APPROVED** [review]

**Comment by msmygit** [comment]
@all-contributors
add @faizalrub-datastax for code content review
add @msmygit for code content doc design maintenance test example ideas promotion review
add @Ankitp1342 for code content doc design maintenance test
add @abinaya21 for code userTesting
add @anoop-datastax for code test
add @weideng1 for code tool test tutorial
add @ssdatastax for doc
add @vaishakhbn for code test

**Comment by msmygit** [comment]
@all-contributors
add @Ankitp1342 for code content doc design maintenance test.
add @abinaya21 for code userTesting.
add @anoop-datastax for code test.
add @weideng1 for code tool test tutorial.
add @ssdatastax for doc.
add @vaishakhbn for code test.

**Comment by msmygit** [comment]
@all-contributors add @anoop-datastax for code test.

**Comment by msmygit** [comment]
@all-contributors add @weideng1 for code tool test tutorial

**Comment by msmygit** [comment]
@all-contributors add @ssdatastax for doc

**Comment by msmygit** [comment]
@all-contributors add @vaishakhbn for code test

**Pull request merged**
